# Generated by Django 4.0.2 on 2022-05-06 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content1',
        ),
    ]
